const products = [
  {
    _id: "1",
    name: "green me alpha",
    image: "/images/veg1.jpg",
    description:
      "Grown in Silvan, these certified organic lebanese cucumbers are amazing, alkalising and refreshing",
    brand: "orgfarm",
    category: "vegetable",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "carrots fresh",
    image: "/images/veg2.jpg",
    description:
      "grown from the central zones of west Africa come with sweet taste",
    brand: "Westfarms",
    category: "vegetable",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Cabbage",
    image: "/images/veg3.jpg",
    description:
      "best cabbage grown by women farmers with over 20years of organic farming ",
    brand: "Cannon",
    category: "bestwomenfarms",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Organic Tomatoes",
    image: "/images/veg4.jpg",
    description: "Sweet delicious organic tomatoes, Victorian Grown",
    brand: "Greenfarms",
    category: "vegetable",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Garden eggs",
    image: "/images/veg5.jpg",
    description: "African garden eggs with full fresh food and spice flavour",
    brand: "bestwomenfarms",
    category: "vegetable",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "green peper",
    image: "/images/veg6.jpg",
    description: "organice blend of African and Canadian origin",
    brand: "sunfarms",
    category: "vegetable",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "beat vegatable",
    image: "/images/veg7.jpg",
    description:
      "known to the indeginous farmers of central Africa, it considered a very good source of health balance diet",
    brand: "orgfarm",
    category: "vegetable",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "8",
    name: "Broccoli",
    image: "/images/veg8.jpg",
    description:
      "Locally grown our organic broccoli is delicious, small heads. Steam, sauté or chop finely and enjoy raw",
    brand: "SunFarms",
    category: "vegetable",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "9",
    name: "onions",
    image: "/images/veg9.jpg",
    description: "summer onions, they grow well in summer and last all year",
    brand: "SunFarms",
    category: "vegetable",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
